ARG BASE_IMAGE=hiyouga/llamafactory:latest
FROM ${BASE_IMAGE}

ARG PIP_INDEX=https://pypi.org/simple

# Change pip source
RUN pip config set global.index-url "${PIP_INDEX}" && \
    pip config set global.extra-index-url "${PIP_INDEX}" && \
    pip install --no-input --no-cache-dir --upgrade pip

# Upgrade tourch
RUN pip install  --no-input --no-cache-dir \
    torch==2.7.1 \
    torchvision==0.22.1 \
    torchaudio==2.7.1

# Install python dependencies, reference: https://github.com/hiyouga/LLaMA-Factory/blob/main/setup.py
RUN pip install --no-input --no-cache-dir \
    'deepspeed>=0.10.0,<=0.16.9' \
    'liger-kernel>=0.5.5' \
    'bitsandbytes>=0.39.0' \
    hqq \
    # eetq \
    # 'optimum>=1.24.0', 'gptqmodel>=2.0.0' \
    'aqlm[gpu]>=1.1.0' \
    'vllm>=0.4.3,<=0.11.0' \
    # 'sglang[srt]>=0.4.5' 'transformers==4.51.1' \
    galore-torch \
    apollo-torch \
    'badam>=1.2.1' \
    adam-mini \
    soundfile vector_quantize_pytorch vocos msgpack referencing jsonschema_specifications \
    swanlab \
    'torchao>=0.8.0' 'accelerate>=1.10.0' \
    unsloth


# Install modelscope dependencies (downgrade some packages)
RUN pip install --no-input --no-cache-dir \
    addict \
    datasets==2.21.0 \
    trl==0.9.6

# Reset pip config
RUN pip config unset global.index-url && \
    pip config unset global.extra-index-url
